# serverless.yml
component: s2-fe-dist # (必填) 引用 component 的名称，当前用到的是 tencent-website 组件
name: s2-fe # (必填) 该 website 组件创建的实例名称
# org: test # (可选) 用于记录组织信息，默认值为您的腾讯云账户 APPID
app: s2h5 # (可选) 该 website 应用名称
stage: test # (可选) 用于区分环境信息，默认值是 dev

inputs:
  src:
    src: ./code
    index: index.html
    # dist: ./dist
    # hook: npm run build
    # websitePath: ./
  region: ap-guangzhou
  bucketName: s2h5
  protocol: https